name: Deploy Frontend via SSH

on:
  push:
    branches: [ "main" ]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Deploy to EC2
        uses: appleboy/ssh-action@v1.2.0
        with:
          host: ${{ secrets.FRONTEND_HOST }}
          username: ubuntu
          key: ${{ secrets.EC2_SSH_PRIVATE_KEY }}
          script: |
            cd /home/ubuntu/LendoGo-frontend
            git fetch --all
            git reset --hard origin/main
            # Write correct env variables
            echo "VITE_API_BASE_URL=${{ secrets.VITE_API_URL }}" > .env
            echo "VITE_WS_BASE_URL=${{ secrets.VITE_API_URL }}" | sed 's/http/ws/' >> .env
            npm install
            npm run build
            sudo systemctl reload nginx