name: Deploy Frontend via SSH

on:
  push:
    branches: [ "main" ]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Deploy to EC2
        uses: appleboy/ssh-action@v0.1.5
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ${{ secrets.EC2_USER }}
          key: ${{ secrets.EC2_SSH_KEY }}
          script: |
            cd /home/ubuntu/LendoGo-frontend
            git pull origin main
            # WRITE THE CORRECT ENV FILE DURING DEPLOYMENT
            echo "VITE_API_URL=${{ secrets.VITE_API_URL }}" > .env
            docker compose down
            docker compose up -d --build